# Generated by Django 6.0.2 on 2026-02-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentstudentconfig',
            name='starting_concepts_by_course',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
