# Generated by Django 6.0.2 on 2026-02-17 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasteryState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_id', models.CharField(help_text='Unique identifier for the concept', max_length=100)),
                ('mastery_score', models.FloatField(default=0.0, help_text='Score from 0.0 to 1.0 indicating mastery level')),
                ('frustration_score', models.FloatField(default=0.0, help_text='Score from 0.0 to 1.0 indicating frustration level')),
                ('attempts', models.IntegerField(default=0, help_text='Number of attempts on this concept')),
                ('last_attempted', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_attempted'],
                'unique_together': {('user', 'concept_id')},
            },
        ),
    ]
