# Generated by Django 6.0.2 on 2026-02-17 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('khan_slug', models.CharField(blank=True, help_text='Khan Academy course slug, e.g. math/algebra-basics', max_length=255)),
                ('grade_level', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['grade_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=120, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.IntegerField(default=1)),
                ('khan_slug', models.CharField(blank=True, help_text='Full Khan Academy URL path', max_length=255)),
                ('quiz_slug', models.CharField(blank=True, help_text='Optional Khan quiz URL path', max_length=255)),
                ('order_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='content.course')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='dependent_concepts', to='content.concept')),
            ],
            options={
                'ordering': ['order_index', 'title'],
                'unique_together': {('course', 'khan_slug')},
            },
        ),
        migrations.CreateModel(
            name='KhanLessonCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('khan_slug', models.CharField(max_length=255, unique=True)),
                ('youtube_id', models.CharField(blank=True, max_length=32)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
